### ISSUE TITLE
Another Error 500 at /wls-exporter/metrics

### ISSUE THREAD

**Issue by dh4pdx** [oracle/weblogic-monitoring-exporter#155] opened 2021-08-04 22:14 UTC
I am using a sample config file that I see displayed on /wls-exporter.
Unlike issue #139, the WebLogic version is 14.1.1.0 and Exporter 2.0.3.  The exporter is deployed on the managed server.

I can see the initial page /wls-exporter correctly , but when I try to access /wls-exporter/metrics I get following error:

####<Aug 4, 2021 7:59:28,226 PM UTC> <Error> <HTTP> <d71df7fec78f> <CSServer> <ExecuteThread: '14' for queue: 'default'> <<WLS Kernel>> <> <684b9686-647b-4ef0-ba18-4d9d0e4fbddc-000000bc> <1628107168226> <[severity-value: 8] [rid: 0] > <BEA-101020> <[ServletContext@567867979[app:wls-exporter module:wls-exporter.war path:null spec-version:4.0]] Servlet failed with an Exception
java.lang.NullPointerException
        at weblogic.servlet.internal.ServletResponseImpl.sendContentError(ServletResponseImpl.java:768)
        at weblogic.servlet.internal.ServletResponseImpl.sendError(ServletResponseImpl.java:826)
        at weblogic.servlet.internal.ServletResponseImpl.sendError(ServletResponseImpl.java:743)
        at com.oracle.wls.exporter.ServletInvocationContext.sendError(ServletInvocationContext.java:71)
        at com.oracle.wls.exporter.AuthenticatedCall.doWithAuthentication(AuthenticatedCall.java:77)
        at com.oracle.wls.exporter.webapp.ExporterServlet.doGet(ExporterServlet.java:47)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:295)
        at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:260)
        at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:137)
        at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:353)
        at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:250)
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3862)
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3829)
        at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:344)
        at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
        at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
        at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
        at weblogic.servlet.internal.WebAppServletContext.processSecuredExecute(WebAppServletContext.java:2502)
        at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2351)
        at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2326)
        at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2304)
        at weblogic.servlet.internal.ServletRequestImpl.runInternal(ServletRequestImpl.java:1779)
        at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1733)
        at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:272)
        at weblogic.work.ExecuteRequestAdapter.execute(ExecuteRequestAdapter.java:21)
        at weblogic.kernel.ExecuteThread.execute(ExecuteThread.java:147)
        at weblogic.kernel.ExecuteThread.run(ExecuteThread.java:119)
>

**Comment by russgold** [comment] 2021-08-16 18:50
This looks like a known problem in WLS 1.4.1.1 that was reported as bug 32133880 and fixed. If you contact support and give them that bug number, they may be able to provide a patched version of WLS for you.

**Comment by dh4pdx** [comment] 2021-08-16 19:36
This is occurring in a docker container running outside of kubernetes (just using docker run). JDK 8 with Amazon Linux. I'm about to change to JDK 11 and if I can get the wls-exporter patched version mentioned by @russgold , I'll try it.

**Comment by russgold** [comment] 2021-08-16 22:35
Let me clarify; wls-exporter is fine. This is a bug in WebLogic Server.

**Comment by dh4pdx** [comment] 2021-08-17 14:09
I understand.  I got the patch for WLS 14.1.1.0 from support and hopefully will apply it and test it today.

**Comment by dh4pdx** [comment] 2021-08-18 19:02
I'm getting the same null pointer exception with the WLS 14.1.1.0 patch and java 11

**Comment by russgold** [comment] 2021-08-19 12:49
Did the stack trace change with the patch? Is this in a standalone or K8S environment? How could I reproduce the issue?

**Comment by PayBas** [comment] 2021-08-19 17:13
I'm getting an incredibly similar error on WLS 12.2.1.4.0

`[ServletContext@60223322[app:wls-exporter module:wls-exporter.war path:null spec-version:3.1], request: weblogic.servlet.internal.ServletRequestImpl@2d48a565[ GET /wls-exporter/metrics HTTP/1.1 Proxy-agent: Oracle-Traffic-Director/11.1.1.9 ECID-Context: 1.8VC_r0EEX00000000;kXjE Surrogate-capability: otd="Surrogate/1.0" User-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8 Accept-language: en-US,en;q=0.7,nl;q=0.3 Accept-encoding: gzip, deflate Upgrade-insecure-requests: 1 Cache-control: max-age=0 X-forwarded-for: 172.28.32.177,10.148.130.1 Via: 1.1 ((domain removed for security reasons)) Connection: keep-alive ]] Root cause of ServletException. java.lang.NullPointerException
at weblogic.servlet.internal.ServletResponseImpl.sendContentError(ServletResponseImpl.java:738)
at weblogic.servlet.internal.ServletResponseImpl.sendError(ServletResponseImpl.java:796)
at weblogic.servlet.internal.ServletResponseImpl.sendError(ServletResponseImpl.java:713)
at com.oracle.wls.exporter.ServletInvocationContext.sendError(ServletInvocationContext.java:71)
at com.oracle.wls.exporter.AuthenticatedCall.doWithAuthentication(AuthenticatedCall.java:77)
at com.oracle.wls.exporter.webapp.ExporterServlet.doGet(ExporterServlet.java:47)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:295)
at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:260)
at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:137)
at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:353)
at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25)
at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
at oracle.security.jps.ee.http.JpsAbsFilter$3.run(JpsAbsFilter.java:175)
at java.security.AccessController.doPrivileged(Native Method)
at oracle.security.jps.util.JpsSubject.doAsPrivileged(JpsSubject.java:315)
at oracle.security.jps.ee.util.JpsPlatformUtil.runJaasMode(JpsPlatformUtil.java:650)
at oracle.security.jps.ee.http.JpsAbsFilter.runJaasMode(JpsAbsFilter.java:112)
at oracle.security.jps.ee.http.JpsAbsFilter.doFilterInternal(JpsAbsFilter.java:293)
at oracle.security.jps.ee.http.JpsAbsFilter.doFilter(JpsAbsFilter.java:150)
at oracle.security.jps.ee.http.JpsFilter.doFilter(JpsFilter.java:94)
at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
at oracle.dms.servlet.DMSServletFilter.doFilter(DMSServletFilter.java:248)
at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
at oracle.jrf.servlet.ExtensibleGlobalFilter.doFilter(ExtensibleGlobalFilter.java:92)
at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3797)
at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3763)
at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:344)
at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2451)
at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2299)
at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2277)
at weblogic.servlet.internal.ServletRequestImpl.runInternal(ServletRequestImpl.java:1710)
at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1670)
at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:272)
at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:655)
at weblogic.work.ExecuteThread.execute(ExecuteThread.java:420)
at weblogic.work.ExecuteThread.run(ExecuteThread.java:360)`

Admittedly, I barely know what I'm doing. I'm just using the example config from https://github.com/oracle/weblogic-monitoring-exporter to see if I can get this up and running.
Not using any Kubernetes stuff. It's a massive Oracle private cloud with lots of OEM/WLS/OSB/SOA stuff.

If this is unrelated to OP, I'll remove. If it's the same bug, let me know if I can help.

**Comment by russgold** [comment] 2021-08-19 17:55
@PayBas That's actually very helpful, as I can see that the error is indeed likely to be in the exporter. 

It looks as though there is an error that it is not handling properly. After you get this, can you navigate to /wls-exporter/messages and send me the output?

**Comment by PayBas** [comment] 2021-08-19 18:39
```
REQUEST to http://removed:80/management/weblogic/latest/serverRuntime/search:
{"links":[],"fields":["name"],"children":{"applicationRuntimes":{"links":[],"fields":["name"],"children":{"componentRuntimes":{"links":[],"fields":["name","type","deploymentState","contextRoot","sourceInfo","openSessionsHighCount"],"children":{"servlets":{"links":[],"fields":["servletName","invocationTotalCount"]}}}}}}}
REPLY:
com.oracle.wls.exporter.ServerErrorException
```

**Comment by russgold** [comment] 2021-08-19 19:27
Thanks. I'll try to have a proposed fix soon.

**Comment by russgold** [comment] 2021-08-19 19:55
@dh4pdx @PayBas I have put a trial fix in branch `issue_155` which you can build and try using the instructions on the main page.

**Comment by PayBas** [comment] 2021-08-19 20:46
@russgold That seems to have worked. No more 500 :)

Now I'm getting a 404 on `wls-exporter/metrics` (whereas `wls-exporter/messages` and the `wls-exporter/` landing page still work), but that's clearly some other problem. Perhaps misconfiguration on my end.

**Comment by dh4pdx** [comment] 2021-08-19 21:16
I'm also getting a 404 error instead of the 500 with wls 14.1.1.0 and java 11

**Comment by russgold** [comment] 2021-08-19 22:16
The 404 is clearly not about the wls-exporter/metrics url, since it is generating the messages. I presume 'removed' is an edit in place of your server name?

Sounds as though I need another diagnostic, but here is the first thing to try: how is your WLS instance configured? Is SSL enabled? What about the domain administration port?

**Comment by russgold** [comment] 2021-08-19 22:23
Also, is the REST query API enabled?

**Comment by PayBas** [comment] 2021-08-19 22:25
Yes, `removed` was for security reasons.

### Domain:
![afbeelding](https://user-images.githubusercontent.com/3015760/130152014-e23bbfed-88f7-4d42-a768-114175868e78.png)

### Server:
![afbeelding](https://user-images.githubusercontent.com/3015760/130151664-689a3f55-9aea-4806-ab6d-d213fbfde2e5.png)

Although there is an admin port override on the server, it appears to only be active if it's active at the domain level, which it isn't.
![afbeelding](https://user-images.githubusercontent.com/3015760/130151733-607d99de-2433-4028-84b1-7c3af182fd23.png)

I tried using:
```
restPort: 8001
queries:
  - key: name
    keyName: server
    applicationRuntimes:
      key: name
      keyName: app
      componentRuntimes:
        type: WebAppComponentRuntime
        prefix: webapp_config_
        key: name
        values: [deploymentState, contextRoot, sourceInfo, openSessionsHighCount]
        servlets:
          prefix: weblogic_servlet_
          key: servletName
          values: invocationTotalCount
```
But that also gives 404 ;)

**Comment by russgold** [comment] 2021-08-19 22:57
OK, let's make sure the REST API isn't the problem. What do you get when you run
```
curl --user <username>:<password> --insecure -d '{"links":[], "fields":[]}' \
       -H "Content-Type: application/json" \
       -H "X-Requested-By: exporter" \
       -X POST http://<host><wls-port>/management/weblogic/latest/serverRuntime/search
```
replacing `<username>` `<password>` `<host>` and `<port>` with the appropriate values?

**Comment by PayBas** [comment] 2021-08-19 23:02
When I use port=80 I get: `{}` (code 200)
When I use port=8001 I get: `curl: (52) Empty reply from server` (no code)

**Comment by russgold** [comment] 2021-08-19 23:08
OK, that suggests that your instance is configured to use port 80 for the REST API - but you used 8001 to access the exporter?

If so, try adding 
```restPort: 80```
to the top of your configuration and try it again.

**Comment by PayBas** [comment] 2021-08-19 23:13
Current Configuration
```
host: dev001-wls.development.local
port: 80
restPort: 80
queries:
- key: name
  keyName: server
  applicationRuntimes:
    key: name
    keyName: app
    componentRuntimes:
      type: WebAppComponentRuntime
      prefix: webapp_config_
      key: name
      values: [deploymentState, contextRoot, sourceInfo, openSessionsHighCount]
      servlets:
        prefix: weblogic_servlet_
        key: servletName
        values: invocationTotalCount
```

Still gives me 404 on http://dev001-wls.development.local/wls-exporter/metrics unfortunately.

**Comment by russgold** [comment] 2021-08-19 23:19
I'm a bit confused about your setup. You're using both port 80 and port 8001? You're using the new console, with which I am unfamiliar, so I cannot tell how your system is set up. I'll have to find somebody who understands it. The exporter expects you to be using a single http port or a single https port that handles both the servlets and the REST api.

**Comment by PayBas** [comment] 2021-08-19 23:24
To be honest, I'm confused as well. I'm relatively new to this whole Oracle cloud stuff. The amount of instances, hierarchy layers, and settings is pretty mind boggling. And we've got all this load-balancing and fail-over stuff which makes it 10x more complex.

I'm using the new console because most of the documentation I see online also uses it. So I thought you would prefer it as well. I usually stick to the old-fashioned looking WebLogic Server Administration Console 12c as well.

**Comment by russgold** [comment] 2021-08-20 00:29
Right, I just need to be able to tell what is going on.

There are two requests happening here:

`http://dev001-wls.development.local/wls-exporter/metrics`  (the exporter)

and 

`http://some-host:80/management/weblogic/latest/serverRuntime/search` (the REST API)

When you got a 200, was `some-host` equal to `dev001-wls.development.local`?

**Comment by PayBas** [comment] 2021-08-20 00:36
@russgold Yes, the `{}` [200] response was from: http://dev001-wls.development.local:80/management/weblogic/latest/serverRuntime/search

**Comment by russgold** [comment] 2021-08-20 00:38
which seems to suggest that you can access the API directly, but the exporter cannot - which makes little sense. Let me see if I can figure out a way to get more info.

**Comment by PayBas** [comment] 2021-08-20 00:39
@russgold Thank you so much for your time and patience. It's getting incredibly late here. I'll have to pick it up tomorrow ;)

**Comment by russgold** [comment] 2021-08-20 02:21
I've updated the branch, so try again to run the exporter and let me know what the messages (and the exporter) report.

**Comment by PayBas** [comment] 2021-08-20 07:56
```
host: dev001-wls.development.local
port: 80
restPort: 80
```
http://dev001-wls.development.local/wls-exporter/metrics gives
`Received status 404 - <html><head><title>Page Not Found</title></head><body>Page Not Found</body></html> `

http://dev001-wls.development.local/wls-exporter/messages gives
```
REQUEST to http://dev001-wls.development.local:80/management/weblogic/latest/serverRuntime/search:
{"links":[],"fields":["name"],"children":{"applicationRuntimes":{"links":[],"fields":["name"],"children":{"componentRuntimes":{"links":[],"fields":["name","type","deploymentState","contextRoot","sourceInfo","openSessionsHighCount"],"children":{"servlets":{"links":[],"fields":["servletName","invocationTotalCount"]}}}}}}}
REPLY:
com.oracle.wls.exporter.ServerErrorException: Received status 404 - <html><head><title>Page Not Found</title></head><body>Page Not Found</body></html>
```

Exact same for `restPort` omitted/none/default.

```
host: dev001-wls.development.local
port: 80
restPort: 8001
```
http://dev001-wls.development.local/wls-exporter/metrics gives
Received status 404 - <html><head><title>Page Not Found</title></head><body>Page Not Found</body></html> 

http://dev001-wls.development.local/wls-exporter/messages gives
```
REQUEST to http://dev001-wls.development.local:8001/management/weblogic/latest/serverRuntime/search:
{"links":[],"fields":["name"],"children":{"applicationRuntimes":{"links":[],"fields":["name"],"children":{"componentRuntimes":{"links":[],"fields":["name","type","deploymentState","contextRoot","sourceInfo","openSessionsHighCount"],"children":{"servlets":{"links":[],"fields":["servletName","invocationTotalCount"]}}}}}}}
REPLY:
com.oracle.wls.exporter.RestPortConnectionException
```

**Comment by russgold** [comment] 2021-08-20 12:45
I don't understand how this is possible, so I must be making an incorrect assumption. What does
```
curl -d '{"links":[], "fields":[]}' \
    -H "Content-Type: application/json" \
    -H "X-Requested-By: exporter" \
    -X POST http://dev001-wls.development.local:80/management/weblogic/latest/serverRuntime/search
```
return? Aside from the security options, is that not what you used yesterday to get the 200 status?

**Comment by PayBas** [comment] 2021-08-20 13:39
@russgold That is correct.

I really feel like it has something to do with the routing:
![image](https://user-images.githubusercontent.com/3015760/130241705-f0783159-b763-46d4-b4c0-caacbd9818dc.png)

I really wish I could override `host`, so that I could try:
```
host: vm-dev001-poc-o-00-wls
port: 80
restPort: 8001
```
That hostname isn't accessible from outside the cluster.

Or just
```
host: localhost
port: 80
restPort: 8001
```

But my attempts to override the auto-generated `host` have failed so far ;)

**Comment by russgold** [comment] 2021-08-20 13:59
OK, so we might be looking at a DNS problem - it could be that `dev001-wls.development.local` is accessible to your DNS but is not accessible from the server itself. The exporter is supposed to be able to handle that, but it's apparently not working in this case.

So here is something you can try: access the exporter from either localhost, if it is on the same machine, or by using its IP address.If that works, we know what is wrong.

**Comment by PayBas** [comment] 2021-08-20 14:06
Bingo!

`curl --user user:password 10.149.96.160:8001/wls-exporter/metrics`

Works from my personal machine.

I cannot SSH to the actual WLS machine (I don't have that kind of permissions), so I cannot inspect the DNS settings.

**Comment by russgold** [comment] 2021-08-20 14:12
OK, I am going to try to add something to diagnose this to make it clear to the user what is happening.

**Comment by PayBas** [comment] 2021-08-20 14:15
@russgold I'm gonna try to hard-code it to `localhost`, to see if that works. Using the IP is not workable for me because those are volatile.

But at least I've got _something_ working :). Thank you so much!

**Comment by PayBas** [comment] 2021-08-22 15:05
Although I managed to edit https://github.com/oracle/weblogic-monitoring-exporter/blob/master/wls-exporter-core/src/main/java/com/oracle/wls/exporter/LiveConfiguration.java#L41-L71 so that the configuration will always return `localhost` as `serverName` as well as for `getLocalHostName()`, and it shows as `localhost` in the `wls-exporter/` landing page, it still tries to resolve to the FQDN when I check `wls-exporter/messages`.

So trying to hard-code the REST url to `localhost` has failed. Using the IP directly works for this particular WLS domain, since it only has `wls_server_1`, but I want to roll this out to more than just our `development` domains.
Our test and (pre)production instances don't even show their IP's. It's all based on FQDN's, and each domain has at least 2 WLS servers (in a cluster). So I guess I'll to talk to our Oracle support about having the FQDN's resolvable from _inside_ the WLS domain.

**Comment by russgold** [comment] 2021-08-23 13:22
The exporter is designed to avoid attempts to misdirect its queries, and is trying to use an API that matches the initial request channel; apparently, that is not working as I'd hoped it would. 

I am first going to find a better way to detect the problem and then see if WLS provides a way to get past this issue.

**Comment by PayBas** [comment] 2021-08-23 18:52
> The exporter is designed to avoid attempts to misdirect its queries, and is trying to use an API that matches the initial request channel; apparently, that is not working as I'd hoped it would.
> 
> I am first going to find a better way to detect the problem and then see if WLS provides a way to get past this issue.

If you need someone to help test your changes, let me know. I'm no WLS expert (as you can probably tell), but I'm very keen to get this working.

**Comment by PayBas** [comment] 2021-08-24 11:30
@russgold I spoke to my support team, and they had the following remarks.

1. `dev001-wls.development.local` is indeed not resolvable from inside the domain/WLS. Whether this is by design or not, is unclear.
2. wls-exporter _should_ route to host `vm-dev001-poc-o-00-wls`, but it probably has no idea how to do that, without being able to specify/override it manually.
3. The `*-wls` hostnames are part of a non-routable IP-range, and can therefore only be used by the platform internally

**Comment by tv3** [comment] 2021-08-24 11:53
@PayBas @russgold I know the cloud platform as I (with collegues) built it. The internal vms have multiple networks. Am I correct to assume the war deployment tries to access the weblogic/jvm via http or t3 instead of mbeans? If so, is there a configurable property that can be set for accessing the internal metrics?

**Comment by PayBas** [comment] 2021-08-25 16:17
@russgold I decided to (temporarily) go with the sidecar/docker setup. Obviously this is not my preferred method, since a single container can only monitor a single WLS target. But without direct override/control of the target REST hostname of the web-app method, it's not workable in our multi-homed environment like tv3 said.

**Comment by russgold** [comment] 2021-12-20 19:09
@dh4pdx The null pointer exception should be resolved by the current changes in the issue_155 branch. I am back to trying to figure out the next problem. Once I have them all resolved, I will merge and probably release a new version.

**Comment by russgold** [comment] 2021-12-23 15:54
I'm trying to figure out how restHost would work. The basic concept here is that with the WAR approach, each server hosts an exporter app which connects back to the REST API on its own server. If we configure a restHost, every managed server's exporter would use the same host name, which would not necessarily be its own server, and thus they would all report the same metrics, unless each server had its own DNS, so that won't work.

Another possibility is to use `localhost` as an alternative to the address sent in the request. The exporter has the ability to try multiple hosts until it finds one that actually represents the REST API, and then stick with that, so possibly using `localhost` as the first guess would work, unless something has been configured oddly. That would not require any additional configuration.

**Comment by russgold** [comment] 2022-01-05 18:19
I've pushed some changes into the main branch to try to address these issues. Among other things, the exporter will try the local address if it cannot otherwise reach the REST API. Please let me know if there are still problems.

**Closed by russgold** 2022-01-05 18:19 UTC
Labels: bug
