### ISSUE TITLE
wls_export accessed in https

### ISSUE THREAD

**Issue by pascalBrand** [oracle/weblogic-monitoring-exporter#96] opened 2020-04-15 15:11 UTC
Hello,

I'm trying to use wls-exporter 1.1.2  in https  and have some issues. Is https supported with this version ?
Thanks
Pascal

**Comment by russgold** [comment] 2020-04-21 12:15
It should be as far as I know. This appears to be a duplicate of your issue #80.

**Closed by russgold** 2020-04-21 12:15 UTC

**Comment by pascalBrand** [comment] 2020-04-28 05:36
I have found some hard coded http:// values in the source code for the REST communication part. I don't think it was ever tested in https.
I changed those values in https because our site in working only in https. It seems to work but I have this issue with the session handling that seems to be due to the usage of the JSESSIONID of the webapp request in the web client REST request. This should be a new session isn't it ?
